### ISSUE TITLE
The extension is not installing from the marketplace

### ISSUE THREAD

**Issue by vishalmry** [dlasagno/vscode-wal-theme#1]
It isn't installing from the marketplace through the command written there
ext install dlasagno.wal-theme
It throws an error that it is incompatible with the VS Code 1.37.1 which is the latest version in Manjaro using bspwm as the window manager.

**Comment by dlasagno** [comment]
This extension at the moment works only on 1.38 and beyond. You need to update the package(on Arch Linux the latest version is available since September 5, on Manjaro it should be already available or coming soon)

**Comment by dlasagno** [comment]
I just released an update that extended support to vscode 1.34, so you should be now able to use it in 1.37.
