### ISSUE TITLE
Doesn't work with vscode remote

### ISSUE THREAD

**Issue by albert-ying** [dlasagno/vscode-wal-theme#14]
Hi! Thank you for this awesome extension! It works perfectly locally. However, the color scheme generated by pywal could not be properly loaded after connecting to the remote machine using `vscode-remote`. It seems that the extension is looking for the pywal cache folder on the remote machine and gives an error when trying to update the theme.

```
Couldn't load colors from pywal cache, be sure to run pywal before updating.
```

I'm wondering if there is any workaround for this as I mostly work on the `vscode-remote`.

Thank you so much!

**Comment by dlasagno** [comment]
I may have found a way to load colors from the local machine, but before implementing the changes, I'd like you to use `Developer: Show Running Extensions` command from the vscode command palette. With that command you should be able to see if this extension is executed locally or remotely, could you tell me the result?

**Comment by albert-ying** [comment]
Interestingly I couldn't find `Wal Theme` in the `Running Extensions` when connected to the remote machine, even though it is installed on the remote machine and the `wal` is set as theme. I also tried to restart but nothing changed.

**Comment by dlasagno** [comment]
If you'd like to help me, could you open the extension folder, open dlasagno.wal-theme and add this property to the package.json:
```
{
    "extensionKind": ["ui", "workspace"]
}
```
In theory this should fix the problem. Let me know if that works.

**Comment by albert-ying** [comment]
> ```
> {
>     "extensionKind": ["ui", "workspace"]
> }
> ```

Amazing, it works! Could you update? Thank you!

**Comment by dlasagno** [comment]
At the moment I'm also working on another issue, and I have two exams this week, so the update will arrive this week, but I don't know when.
Thank you for trying the solution for me.

**Comment by albert-ying** [comment]
Sure, no rush at all. It already works perfectly for me with that one-line patch. Again, thank you for your efforts on this and good luck with your exam!

**Comment by dlasagno** [comment]
Version 1.1.0 is out now and added support for vscode remote.

If the problem persists feel free to re-open this issue and I will be more than happy to help you.
