### ISSUE TITLE
Extension seems to update one behind when wal changes

### ISSUE THREAD

**Issue by micahsoftdotexe** [dlasagno/vscode-wal-theme#16]
Greetings,
I apologize for any confusion in the wording, this is quite hard for me to explain. 

The problem is that when creating a new theme with pywal, the first time I create a new theme after opening code, the theme of code will not change, but after the second change, the theme will change to the theme that was created by the first change, thus being always one theme behind. This can be corrected by manually updating the theme via a command.
I have attached a video giving a bit of a demonstration of what I mean.

https://user-images.githubusercontent.com/58262074/129638319-785b5aa0-15af-4125-900e-8928a9b039ee.mp4

**Comment by dlasagno** [comment]
It looks like it could be a problem with the detection of changes in pywal theme.
I'll look into this when I can.
Probably it has to do with how node watches files.

**Comment by dlasagno** [comment]
The problem should be now fixed in 1.1.2. If you still find that after the update this behavior persists, then please re-open this issue. and I'll try my best to help you.
