### ISSUE TITLE
Add to Open VSX repository

### ISSUE THREAD

**Issue by MisterChief53** [dlasagno/vscode-wal-theme#18]
Lots of open source extensions are being added to that repository. This is useful for onivim users like me, since the project seeks to support vscode extensions, but only pulls from that repo. 

Relevant links: 
https://onivim.github.io/docs/configuration/extensions
https://open-vsx.org/
https://www.eclipse.org/community/eclipse_newsletter/2020/march/1.php

I am not suggesting some kind of code rework or bugfix, just the ability to download the extension from there.

**Comment by dlasagno** [comment]
I'll look into this after I release a new version to fix another issue that is currently open.

**Comment by dlasagno** [comment]
This extension is now available on the Open VSX Registry.
