### ISSUE TITLE
Background color difference

### ISSUE THREAD

**Issue by albert-ying** [dlasagno/vscode-wal-theme#21]
<img width="1872" alt="image" src="https://user-images.githubusercontent.com/59846322/192653407-8edd9767-f22c-4489-be74-0aba3fba07be.png">

The background color is different in the area with text and without text.

In the attached screenshot, the left side is lighter than the right side.

I check the template, could not figure out why -- maybe you can shade some light on this... Thank you!

**Comment by dlasagno** [comment]
Hi, sorry for taking this long to address your issue. Your case is curious: I don't know how to reproduce your problem, but I'm noticing that something is off in your screenshot: in my vscode, there's a lateral bar on the right that shows the whole file. You're also missing the scrollbar.
![image](https://user-images.githubusercontent.com/25227413/201621266-7165afb0-495c-4bea-86ba-ba91eb24249b.png)
After taking a closer look it also seems that the darker region is smaller than the editor tab. Could it be some other extension or setting that you previously activated?

**Comment by dlasagno** [comment]
I'm closing the issue for inactivity. Feel free to re-open it if needed.
