### ISSUE TITLE
Black background if color.json present

### ISSUE THREAD

**Issue by g0josh** [dlasagno/vscode-wal-theme#22]
Hi, I am tweaking the colors a bit by my own in files `~/.cache/wal/colors` and `~/.cache/wal/colors.json`. Theme works perfectly fine if I don't have `colors.json`, but presents a black background if that file is present. `colors.json` is required for `pywalfox` that I use to theme firefox. The theme works if I use the files generated by `wal` and donot edit them. Could you please point me in the right direction. 
Here are my `colors.json` and `colors` files,

```
{
    "wallpaper": "/home/job/.config/themes/walls/shuttle.png",
    "alpha": 100,
    "special": {
        "foreground:": "#e3dad1",
        "background:": "#0c080d",
        "cursor": "#e3dad1"
    },
    "colors": {
        "color0:": "#0c080d",
        "color8:": "#9e9892",
        "color1:": "#911728",
        "color9:": "#b72520",
        "color2:": "#57293b",
        "color10:": "#c05a82",
        "color3:": "#ba5622",
        "color11:": "#fa752f",
        "color4:": "#224260",
        "color12:": "#2087e6",
        "color5:": "#94605d",
        "color13:": "#ff857e",
        "color6:": "#7b8689",
        "color14:": "#21cfff",
        "color7:": "#e3dad1",
        "color15:": "#e3dad1"
    }
}
```
```
#0c080d
#911728
#57293b
#ba5622
#224260
#94605d
#7b8689
#e3dad1
#9e9892
#b72520
#c05a82
#fa752f
#2087e6
#ff857e
#21cfff
#e3dad1
```

**Comment by dlasagno** [comment]
Hi, could you provide a diff between the original colors.json/colors and the ones that you edited?
Also a quick note: wal theme just picks the special.background and special.foreground colors from the colors.json at the moment.

**Comment by dlasagno** [comment]
I'm closing the issue for inactivity. Feel free to re-open it if needed.
