### ISSUE TITLE
Template file modification does not register

### ISSUE THREAD

**Issue by Teenarp2003** [dlasagno/vscode-wal-theme#25]
hi, i m trying to modify the template file that generates the wal and wal-bordered color schemes. i am modifying the file in  ~/.vscode/extensions/{extension dir}/out/template.js     
However thes modifications fo not register and the theme is generated for the original color specified, not the new color number. I tried changing the out/src/template.js file but to no avail. 

Can you provide me some insight into this?

**Comment by dlasagno** [comment]
Hi, just to make sure that I understand your problem, what is it that you're trying to achieve? From my understanding it seems that you're trying to change which of the 9 colors provided by pywal is being used for a certain ui element, is that correct?

**Comment by Teenarp2003** [comment]
Yes I am trying to change the activity bar foreground color. I changed the color code values. 
I reloaded the theme and vscode but the changed colors did not reflect. 

Seems like the modification only takes effect after one reboot.

**Comment by dlasagno** [comment]
Yes, the theme updates only when vscode boots or when the wal file gets updated. You can manually reload the theme through the command. You can find it in the README. Remember that the file you're modifying is called only in those occasions to generate the actual file(the json one), so you won't see the changes applied until the theme updates.
If you don't have any further questions I'll consider this issue solved.

**Comment by Teenarp2003** [comment]
Okay. thank you for your time.
