### ISSUE TITLE
Missing color in syntax highlighting

### ISSUE THREAD

**Issue by henrispkl** [dlasagno/vscode-wal-theme#3]
So, I noticed that the theme generated by the extension has a simple syntax highlighting. It happens to be that it uses the same color for two types of highlighted things. For example, in JavaScript files, the same color used in reserved keywords (const, let, var, import etc) is also used in function names.

![img1](https://user-images.githubusercontent.com/44950242/65820803-d6522e00-e203-11e9-87bd-9f8f65d71d30.png)

While in basically any other theme for VSCode, each has it's own color (this theme here is Dracula.min)

![img2](https://user-images.githubusercontent.com/44950242/65820824-039edc00-e204-11e9-8a4f-c263d9eb28b0.png)

Something similar occurs in HTML files, where the tag names uses the same color as the property values from an element.

![img3](https://user-images.githubusercontent.com/44950242/65820876-89228c00-e204-11e9-8f99-c16306890bd6.png)
![img4](https://user-images.githubusercontent.com/44950242/65820877-8aec4f80-e204-11e9-9cb1-472a2b034e04.png)

By the way, here's the colors from the scheme that Pywal generated.

![img5](https://user-images.githubusercontent.com/44950242/65820890-d30b7200-e204-11e9-974a-4a8d93b88d41.png)

**Comment by dlasagno** [comment]
Thanks a lot for reporting this issue and for being so detailed.
The problem is that pywal gives 6 colors to use, so the function name color will match another color anyway, though probably matching keywords isn't really good. Hopefully in the next days I will fix this(I'm thinking of using the same color of operators, we'll see). If you find any other problem like this I would really appreciate a report like this, thanks again.

**Comment by dlasagno** [comment]
@henrispkl I just finished looking into this. Could you test the new version and tell me if anything is wrong?
Here's the link: https://drive.google.com/open?id=1ub240x3CxnP85wWbIE4uh_CAIwkvQ8KR

**Comment by henrispkl** [comment]
It looks very good now! However, it's still the same for HTML files. But here's a suggestion: taking a look into the code, I've managed to find where to change the color of the tag names, so I just changed it from color 2 to color 5 and it looks very good with this change!

![c](https://user-images.githubusercontent.com/44950242/65982947-d5630b80-e452-11e9-93bf-0104a6af267b.png)

![c2](https://user-images.githubusercontent.com/44950242/65982705-4fdf5b80-e452-11e9-92b6-b91445a7de50.png)

I still think that there could be improvements on which colors are used to color variables, strings, keywords, operators etc, but it's not related to this issue at all.

I don't know much about VSCode theming, but I may fork this repo in the future to try a different approach for each color.

Edit: oops, I accidentally closed this issue, haha. I'm new to Github so I don't know if this is the right thing to do since this issue is "resolved".

**Comment by dlasagno** [comment]
Thanks for your help, the new version will be online by the end of this week(it depends on when I have time).
PS: probably I will also take a look at html tags, but I'm not going to touch the rest in the near future, also keep in mind that what looks good with your wallpaper may look bad with another wallpaper, so the important thing is just to vary the color used.
