### ISSUE TITLE
What's the best way to modify which colors are used for comments and line numbers

### ISSUE THREAD

**Issue by cjstock** [dlasagno/vscode-wal-theme#5]
As you can see in these screenshots, it's almost impossible to see the comments and line numbers. What's the best way to change which color is used for these elements? I was going to modify individual color schemes through wal or wpg, but I notice the problem happens with every scheme, so I'd rather do it another way.

![Screenshot from 2020-01-13 13-57-59](https://user-images.githubusercontent.com/7853471/72295658-e0f6ce80-360c-11ea-8b27-954ef6134fbe.png)

![Screenshot from 2020-01-13 14-02-22](https://user-images.githubusercontent.com/7853471/72295944-67abab80-360d-11ea-9a8c-12a43e531319.png)

**Comment by dlasagno** [comment]
Before touching the code, have you tried with different wallpapers? As you can see in the README, the comments should be visible.

If that doesn't work the options are:
- manually change the color file in pywal cache(specifically the nineth color), keep in mind that this file is updated by pywal every time you run it(to avoid this you can make a template)
- the second option is to change template.ts in the extension folder to use a different color for comments and line numbers(this file is updated with the extension though)

Those are just some quick fixes, but if the problem doesn't go away by trying a different wallpaper, I would like to ask you to put here the exact command you use for pywal and a full screenshot of vscode. Thank you for the cooperation.

**Comment by cjstock** [comment]
I've tried like 10 different wallpapers, and all of them seem to have the issue.

I'll just change the color file for each wallpaper, I guess. Your extension is fantastic, by the way.

**Comment by dlasagno** [comment]
Could you try changing the following lines in `$HOME/.vscode/extensions/dlasagno.wal-theme-1.0.3/out/template.js` from this:

```javascript
'editorLineNumber.foreground': colors[8].hex() + '92',
'editorLineNumber.activeForeground': colors[8].hex(),

// ...

{
  'name': 'Comment',
     'scope': ['comment'],
     'settings': {
        'fontStyle': 'italic',
        'foreground': colors[8].hex() + 'b0'
      }
},
```

to this:

```javascript
'editorLineNumber.foreground': colors[7].hex() + '92',
'editorLineNumber.activeForeground': colors[7].hex(),

// ...

{
  'name': 'Comment',
     'scope': ['comment'],
     'settings': {
        'fontStyle': 'italic',
        'foreground': colors[7].hex() + 'b0'
      }
},
```

This should make your comments and line numbers more bright. Also, if you don't mind, would you send me the exact command you use for pywal and a full screenshot of vscode?

**Comment by cjstock** [comment]
Those changes worked!

I don't use pywal directly. I use wpgtk: https://github.com/deviantfero/wpgtk

wpgtk uses pywal to generate colorschemes. I now realize the reason I'm having this issue with your extension is because I have colorz set as the backend in wpgtk. Your theme is tuned for the color schemes generated by pywal, and mine are instead generated by colorz, so the schemes are different.

Here are the some screen shots showing the fixed issue:
![image](https://user-images.githubusercontent.com/7853471/72544302-f7cf3800-383b-11ea-9057-6ef71c4add48.png)
![image](https://user-images.githubusercontent.com/7853471/72544375-17666080-383c-11ea-8781-56c493adc258.png)

As a side note, I noticed the wallpapers you used in your read me and added a bunch of hers to my collection.

**Comment by dlasagno** [comment]
Happy to hear that.
The changes that I gived you will be overwritten by any future update to the extension tough. I recommend you to not rely on them. If changing the backend is enough, then I can consider this issue closed.
